services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-gorilla
    env_file:
      - ../.env.local
    ports:
      - "5000:5000"
    networks:
      - waect-network
    depends_on:
      database:
        condition: service_healthy

networks:
  waect-network:
    driver: bridge
    external: true
  
