# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"
gem 'puma'
gem 'sinatra'

gem 'rackup', '~> 2.1'

gem 'activerecord', '~> 7.1'

gem 'sinatra-activerecord', '~> 2.0'

gem 'rake', '~> 13.1'

gem 'bcrypt', '~> 3.1'

gem 'sinatra-flash', '~> 0.3.0'

gem 'pg', '~> 1.5'

gem 'newrelic_rpm', '~> 9.7'

gem 'dotenv', '~> 3.1'

group :development do
  gem 'bundler-audit'
  gem 'lefthook'
  gem 'rubocop', '~> 1.62', require: false
  gem 'rubocop-rake', require: false
  gem 'rubocop-rspec'
  gem 'rubocop-shopify', require: false
  gem 'ruby-lsp'
end

gem 'sinatra-namespace', '~> 1.0'

gem 'rubocop-packaging', require: false
