services:
  ruby-sinatra:
    image: waect/ruby-sinatra
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ../.env.local
    networks:
      - waect-network

networks:
  waect-network:
    external: true